### ISSUE TITLE
1988 Texan Showdown

### ISSUE THREAD

**Issue by WNDIUA** [campaign-trail-showcase/campaign-trail-showcase.github.io#106]
Name: 1988 ~ Texas Showdown

Code 1: https://gist.githubusercontent.com/WNDIUA/986991ed618655b307accdc51c76dcdb/raw/cde781f0e2f9d68bf8c79aa77d8534432c9a6bd6/Code%25201%2520Texas%2520Showdown%2520Showcase

Code 2 Biden:  https://gist.githubusercontent.com/WNDIUA/6d2dafa4a83fe6efeee9f846ef8e51db/raw/54021f96deaeff247843438371fa3d3ee31a86bf/Code%25202%2520Biden

Code 2 Tsongas: https://gist.githubusercontent.com/WNDIUA/f50e98a68e888ac130dba8ce5e7951f8/raw/77bab8c02115c2b26caada2169c970643f9f218c/Code%25202%2520Tsongas

Code 2 Glenn: https://gist.githubusercontent.com/WNDIUA/5edf7329bb08c7657b8ddac344dc679d/raw/820301d7c80d99fc10ce315015df23d5cbb5f9fe/Code%25202%2520Glenn

**Comment by JetSimon** [comment]
Please name the files in the format DisplayYear_CandidateLastNameRunningMateLastName next time if you can!

Ex: 1988Texans_BentsenBiden.html

Added
