### ISSUE TITLE
Mod Submission

### ISSUE THREAD

**Issue by CordaRoy38** [campaign-trail-showcase/campaign-trail-showcase.github.io#108]
Mod Name: 1998NY
Best Place to Contact You: Accurate_Feature9970
Link to Code 1: https://github.com/CordaRoy38/CSMods.git (Has Code1)
Link to Code 2: https://github.com/CordaRoy38/CSMods.git (Has Code2)
Description/Additional Info (Optional): Idk if the achievements work, I added them and they didn't bug out the gameplay in any way so I assume they're finalized on your end. Also for the theme colors on the main screen where you select the mod, just make them the same as the 2022NY mod.

**Comment by JetSimon** [comment]
For the theme you need to add it to your code 1. Instructions work here.

Custom mods on the site have achievements so you can test if they work. Please test.

https://github.com/campaign-trail-showcase/campaign-trail-showcase.github.io/blob/main/How%20Tos/How%20to%20Add%20Custom%20Themes%20To%20Your%20Mod's%20Box.md

**Comment by CordaRoy38** [comment]
Mod box done, turns out already had it.

Would the achievements for custom mods pop up as they do for other mods?

**Comment by JetSimon** [comment]
They should just pop up. You can tell if they are in if they show up in the achievements menu after you add the custom mod.

**Comment by CordaRoy38** [comment]
Couldn't figure out the issue so took them out. Mod should be done otherwise.
