### ISSUE TITLE
Please stop breaking Benefit Check

### ISSUE THREAD

**Issue by Wolf-in-the-Mask** [campaign-trail-showcase/campaign-trail-showcase.github.io#11]
The Benefit Check does not work - this was the case earlier today (when Achievements were added), then was fixed, then this error is back again.

**Comment by JetSimon** [comment]
Could you post the error? I haven't seen it

**Comment by JetSimon** [comment]
It works for me on my computer. Are you on mobile?

**Comment by Wolf-in-the-Mask** [comment]
I'm so sorry, it turns out the issue was completely on my end - I use three keyboard layouts, and the tilde is present only in one of them. Stay pawsome and sorry for wasting your time!

**Comment by JetSimon** [comment]
All good. Alternatively you can use `.
