### ISSUE TITLE
Pull request for 2017 UK

### ISSUE THREAD

**Issue by theVVaves** [campaign-trail-showcase/campaign-trail-showcase.github.io#110]
Mod Name: 2017
Best Place to Contact You: Discord @ warandpeaches
Link to Code 1: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_init.html)
Link to Code 2 Old Labour: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_LabourOld%20Labour.html)
Link to Code 2 Big tent Labour: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_LabourBig%20Tent%20Labour.html)
Link to Code 2 Lexiteer Labour: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_LabourLexiteer%20Labour.html)
Link to Code 2 Progressive Labour: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_LabourProgressive%20Labour.html)
Link to Code 2 Cosmopolitan Labour: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_LabourCosmopolitan%20Labour.html)
Link to Code 2 Hard Brexiteer Tories: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_ConservativesHard%20Brexiteer.html)
Link to Code 2 Soft Brexiteer Tories: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_ConservativesSoft%20Brexiteer.html)
Link to Code 2 Mainstream Tories: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_ConservativesMainstream%20Conservative.html)
Link to Code 2 One Nation Tories: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_ConservativesOne-Nation%20Conservative.html)
Link to Code 2 Thatcherite Tories: [LINK HERE](https://github.com/newcampaigntrail/newcampaigntrail.github.io/blob/main/static/mods/2017%20UK_ConservativesThatcherite%20Conservative.html)
Description/Additional Info (Optional): [Original release post on TCT subreddit](https://old.reddit.com/r/thecampaigntrail/comments/15wl6e4/mod_release_2017_uk/). Mod has been on New Campaign Trail for awhile, one of the deepest gameplay-wise for sure.

**Comment by JetSimon** [comment]
You are not the mod maker though right?
