### ISSUE TITLE
Pull Request for 1964 Bennett

### ISSUE THREAD

**Issue by WNDIUA** [campaign-trail-showcase/campaign-trail-showcase.github.io#111]
Code 1: https://gist.githubusercontent.com/WNDIUA/ba8f05a86723815aacb897cfbe5a3cbc/raw/78ff8daa88e840ff35a3045888e643d3c7230136/Updated%2520Code%25201

Code 2 Ford: https://gist.githubusercontent.com/WNDIUA/e3e9754588f2877a1aa23ca928711884/raw/05d0c64429caead86eb98bd1b31d36cdf1566662/Code%25202%2520for%2520Ford%2520Updated

Code 2 Cooper: https://gist.githubusercontent.com/WNDIUA/3d065a65e28b091c468a325a609ed21d/raw/b83b42c2c672eb1c2465809b526fbb96e7cdbc10/Code%25202%2520for%2520Cooper

Code 2 Lodge: https://gist.githubusercontent.com/WNDIUA/faaf9ce49cd47db8d288d35557e8e752/raw/ea20bc1c83eb9cecec29f768494a6b87021f5dfa/Code%25202%2520for%2520Lodge

Also, if you could, for the title could you call it: 1964 Bennett ~ Let Liberty Free

**Comment by JetSimon** [comment]
Added. Please try to name files as they are in the mods folder in the future for faster addition.
