### ISSUE TITLE
2004 Joementum

### ISSUE THREAD

**Issue by WNDIUA** [campaign-trail-showcase/campaign-trail-showcase.github.io#116]
Pull Request for 2004 Joementum

Code 1: https://gist.githubusercontent.com/WNDIUA/8a35d0b09664f170b92521775be37a48/raw/f01b1194d82a5fd22a34a9698e507f154c56aa10/gistfile1.txt

Code 2 Graham: https://gist.githubusercontent.com/WNDIUA/8fd919e1fed3b7b07778363356cdc2c5/raw/8e49b1cd990c943ffaa933eaeaa6fad343c3f9f8/Code%25202%2520Graham

Code 2 Breaux: https://gist.githubusercontent.com/WNDIUA/8aefc24f898220cafcd715458069faf9/raw/e48beadd0eb5123eb0aedf7f755cf5f15d8de601/Code%25202%2520Breaux

Code 2 Durbin: https://gist.githubusercontent.com/WNDIUA/36458799cc58287b0ce8578307411c9f/raw/a1b30750a429c3943cf103a4c35ccdae361fa660/Code%25202%2520Durbin

For the mod title, could it be 2004 ~ Joementum

Thank you.

**Comment by JetSimon** [comment]
Hello,

Please resubmit through this form: https://campaign-trail-showcase.github.io/campaign-trail/submit.html
