### ISSUE TITLE
2012: Outsider Comes Early

### ISSUE THREAD

**Issue by EnvironmentalCap104** [campaign-trail-showcase/campaign-trail-showcase.github.io#12]
Mod Name: 2012: Outsider Comes Early
Best Place to Contact You: Environmental_Cap104 (Discord and Reddit)
Link to Code 1: (https://github.com/EnvironmentalCap104/2012T/blob/main/2012T_init.html)
Link to Code 2: (https://github.com/EnvironmentalCap104/2012T)
Description/Additional Info (Optional): Donald Trump, the 45th president of the United States, comes in a couple of years early. While seen mostly as a joke throughout the 2012 Republican Primaries, he is somehow able to get past the primaries, and now faces incumbent President Obama. Does he shock the country and become President, or is Obama gonna defeat him handily? *NOTE: This is NOT a sequel to Trump 2008.

**Comment by JetSimon** [comment]
Hey,

Thanks for the submission! The team has played through it and we have a few concerns before we could approve it:

* Image stretching during the code 1 screen
 
* Some weird phrasing in questions. May need another pass.

However: We are soon to be adding another section to the site called Community Mods. Where the current selection of mods will be in Featured Mods.

If you do not mind being in that selection as opposed to Featured we can approve it as is, and it will be added in the coming days.

Let me know if you have any questions!

**Comment by EnvironmentalCap104** [comment]
I can go into the Community section. Same with Arnold.

**Comment by JetSimon** [comment]
In the Community section! Congrats on being the first one
