### ISSUE TITLE
2017 UK - Lexiteer not working

### ISSUE THREAD

**Issue by Wolf-in-the-Mask** [campaign-trail-showcase/campaign-trail-showcase.github.io#127]
Hello there!

A problem with hopefully a quick fix - the Lexiteer side for Corbyn in the 2017 UK scenario doesn't work - you're unable to progress past the first option. Console says this:
![image](https://github.com/campaign-trail-showcase/campaign-trail-showcase.github.io/assets/41969980/8ef0482b-25c3-4f09-982b-7e6d2dbc8d2e)

Thank you in advance!

**Comment by JetSimon** [comment]
I was able to progress. Let me know if it still happens for you.
