### ISSUE TITLE
2016: Arnold Amendment

### ISSUE THREAD

**Issue by EnvironmentalCap104** [campaign-trail-showcase/campaign-trail-showcase.github.io#13]
Mod Name: 2016: Arnold Amendment
Best Place to Contact You: Environmental_Cap104 (REDDIT AND DISCORD)
Link to Code 1: (https://github.com/EnvironmentalCap104/2016ARNOLD-Code-1)
Link to Code 2: (https://github.com/EnvironmentalCap104/2016ARNOLD-Code-2)
Description/Additional Info (Optional): The Equal Right to Govern Amendment passes in 2014, and two naturalized politicians go up against each other in 2016. Former Republican California Governor Arnold Schwarzenegger faces off against former Democratic Michigan Governor Jennifer Granholm. There is also a third-party conservative ticket led by former Republican Arkansas Governor Mike Huckabee, but isn't playable.

**Comment by JetSimon** [comment]
Hello again,

As with the other mod, we have some similar concerns:

* Image stretching during the code 1 screen

* Some weird phrasing in questions. May need another pass.

Again we CAN put this in the Community section if you don't want to make these changes. Just let us know!

Thanks,

Jet

**Comment by JetSimon** [comment]
It is being added very soon. It will be a button that you press at the top to switch between Showcase and Community.

**Comment by JetSimon** [comment]
In community section!
