### ISSUE TITLE
Mouths of the South second patch

### ISSUE THREAD

**Issue by CordaRoy38** [campaign-trail-showcase/campaign-trail-showcase.github.io#137]
[Code 1](https://raw.githubusercontent.com/CordaRoy38/CSMods/main/1996%20-%20Mouths%20of%20the%20South%20(Patch))

[Code 2 Kohl](https://raw.githubusercontent.com/CordaRoy38/CSMods/main/1996%20-%20Mouths%20of%20the%20South_TurnerKohl%20(Patch))

[Code 2 Jackson](https://raw.githubusercontent.com/CordaRoy38/CSMods/main/1996%20-%20Mouths%20of%20the%20South_TurnerJackson%20(Patch))

[Code 2 Kerry](https://raw.githubusercontent.com/CordaRoy38/CSMods/main/1996%20-%20Mouths%20of%20the%20South_TurnerKerry%20(Patch))

**Comment by JetSimon** [comment]
Added. You forgot an if at the start of your code 1 but I added it so the music player is fixed (tested).
