### ISSUE TITLE
Jackson and Kerry MOTS quick fix

### ISSUE THREAD

**Issue by CordaRoy38** [campaign-trail-showcase/campaign-trail-showcase.github.io#139]
Html error broke Jackson and Kerry paths in last patch, apologies

[Jackson](https://raw.githubusercontent.com/CordaRoy38/CSMods/main/1996%20-%20Mouths%20of%20the%20South_TurnerJackson%20(Patch))

[Kerry](https://raw.githubusercontent.com/CordaRoy38/CSMods/main/1996%20-%20Mouths%20of%20the%20South_TurnerKerry%20(Patch))

**Comment by ItsAstronomical** [comment]
AFAIK jet added this fix, reopen if its still bugged
