### ISSUE TITLE
1948Red Submission

### ISSUE THREAD

**Issue by CaptainTom707** [campaign-trail-showcase/campaign-trail-showcase.github.io#14]
Mod Name: 1948Red
Best Place to Contact You: captaintom on Discord
Placement: Featured
Link to Code 1: [LINK HERE](https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-1.txt)
Link to Code 2s:
1948Red Wallace/Rayburn Code 2 - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Wallace.txt

1948Red Wallace/Roosevelt Code 2 - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Wallace_Roosevelt.txt

1948Red Wallace/Byrnes Code 2 - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Wallace_Byrnes.txt

1948Red Wallace/Taylor Code 2 - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Wallace_Taylor.txt

1948Red Stassen/Vandenberg Code 2 - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Stassen.txt

1948Red Stassen/Saltonstall Code 2 - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Stassen_Saltonstall.txt

1948Red Stassen/Marshall Code 2 - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Stassen_Marshall.txt

1948Red Stassen/Willis Code 2 - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Stassen_Willis.txt

1948Red Russell/Thurmond - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Russell.txt

1948Red Russell/MacArthur - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Russell_MacArthur.txt

1948Red Russell/Byrd - https://gitlab.com/ItsJustAiden/1948Red/-/raw/main/1948Red_Code-2_Russell_Byrd.txt
Description/Additional Info (Optional):

**Comment by JetSimon** [comment]
Featured!
