### ISSUE TITLE
Pull Request for 1988 Rainbow Trail

### ISSUE THREAD

**Issue by WNDIUA** [campaign-trail-showcase/campaign-trail-showcase.github.io#146]
Code 1: https://gist.githubusercontent.com/WNDIUA/bede365f1046b26ce9ba8f653c84de4a/raw/e40c6cdf1f9e389d5f7a1f5f4174961088d29715/Rainbow%2520Code%2520for%2520Showcase

Code 2 Levin: https://gist.githubusercontent.com/WNDIUA/9ab6ddf563c5624eca7b36439fbca55a/raw/8007280ec9da05d5e38ce438b54033c3c9bcbfde/Code%25202%2520Levin

Code 2 Leahy: https://gist.githubusercontent.com/WNDIUA/4af8e964382a2fc5ff804534e17ed825/raw/67d381c205af180c62ffaa90c94e5608b186626f/Code%25202%2520Leahy

Code 2 Pell: https://gist.githubusercontent.com/WNDIUA/db984d18b7a8e82141d360b7b3c8cd48/raw/7213c8adeda9d2c655bd7ff794e9f596b4b379a5/Code%25202%2520Pell

Code 2: Hollings: https://gist.githubusercontent.com/WNDIUA/1133695fad7a732ccb3d3767fa4f78f2/raw/aa10dfbbfdd7b43d106674ada7b30b022bc77f55/Code%25202%2520Hollings

**Comment by JetSimon** [comment]
Please try to use the form first
