### ISSUE TITLE
1952Red Submission

### ISSUE THREAD

**Issue by CaptainTom707** [campaign-trail-showcase/campaign-trail-showcase.github.io#15]
Mod Name: 1952Red
Best Place to Contact You: captaintom on Discord
Placement: Featured
Link to Code 1: [LINK HERE](https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-1.txt)
Link to Code 2s:
1952Red Code 2: Stassen/Knowland — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_Stassen_Knowland.txt

1952Red Code 2: Stassen/Warren — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_Stassen_Warren.txt

1952Red Code 2: McMath/Kefauver — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_McMath_Kefauver.txt

1952Red Code 2: McMath/Truman — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_McMath_Truman.txt

1952Red Code 2: McMath/Acheson — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_McMath_Acheson.txt

1952Red Code 2: McMath/Chandler — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_McMath_Chandler.txt

1952Red Code 2: McMath/Williams — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_McMath_Williams.txt

1952Red Code 2: McMath/Hill — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_McMath_Hill.txt

1952Red Code 2: McMath/Douglas — https://gitlab.com/ItsJustAiden/1952red/-/raw/main/1952Red%20Files/1952Red_Code-2_McMath_Douglas.txt
Description/Additional Info (Optional):

**Comment by JetSimon** [comment]
Featured!
