### ISSUE TITLE
1960Kennedy - Code 2 doesn't load

### ISSUE THREAD

**Issue by Wolf-in-the-Mask** [campaign-trail-showcase/campaign-trail-showcase.github.io#162]
Hello, it seems that because of the recent commits, code 2 for 1960Kennedy mod no longer works, it just uses the vanilla, Dan Bryan's 1960 code 2 for Kennedy/Humphrey. 

Hope you can figure out what caused this, Simon!
![image](https://github.com/campaign-trail-showcase/campaign-trail-showcase.github.io/assets/41969980/9e13683d-d2a5-4522-8ad1-b29f96591f27)

**Comment by JetSimon** [comment]
Thanks for the report. Fixed.
