### ISSUE TITLE
1845: Utopian and Locofoco Map Issues

### ISSUE THREAD

**Issue by joesdd** [campaign-trail-showcase/campaign-trail-showcase.github.io#199]
The 1845: Utopian and Locofoco election has an issue where if you open the map at any point you cannot return to the questions. You also cannot progress to the ending screen/results, as the pop-up to see the final map doesn't go away.

**Comment by ItsAstronomical** [comment]
I cannot seem to recreate this issue. Are you checking the map right as you start the mod?
