### ISSUE TITLE
Mod Submission: Sumner 68 Redux

### ISSUE THREAD

**Issue by CaptainTom707** [campaign-trail-showcase/campaign-trail-showcase.github.io#20]
Mod Name: Should be displayed on the loader as "Sumner 68 Redux"
Best Place to Contact You: captaintom on Discord
Placement: Prefer featured.  If joke mods can't go there (other than Bateman), community's cool too.
Link to Code 1: [LINK HERE](https://gitlab.com/TomStassen/sumner68redux/-/raw/main/68_Sumner_Redux.txt)
Link to Code 2 [LINK HERE](https://gitlab.com/TomStassen/sumner68redux/-/raw/main/68_Sumner_Code_2.txt)
Description: In this redux of the classic community gem by u/No-Damage2000, step into the shoes of incumbent president Charles Sumner as he staves off opposition by the "Bellum" faction of the southern states who oppose his radical reconstruction program, their standard-bearer being none other than Andrew Johnson.  Should he win re-election, he will prove to the American people and all history the vindication of his signature programs and courageous spirit.
Additional info: This mod should be in the "1960s-1970s" tab.

**Comment by JetSimon** [comment]
Passed with 1 No 4 Yes 1 Abstain
