### ISSUE TITLE
Mod Request

### ISSUE THREAD

**Issue by metheguytct** [campaign-trail-showcase/campaign-trail-showcase.github.io#21]
Mod Name: 2000N
Best Place to Contact You: U/StingrAeds
Placement:Featured
Link to Code 1: [LINK HERE](https://docs.google.com/document/d/1I_oVQPA6mfFSFYaaenAKHMrM81igJI0s2KdT-S8N35U/edit)
Link to Code 2 [LINK HERE](https://docs.google.com/document/d/1ctlBibGn3mlEM-_AwhPVkz_k4fU8U3ppxQfui37zcW4/edit?usp=sharing),  [
](https://docs.google.com/document/d/1oMR1wAqGfeoUmGDTM2ufnoos4aPGpjcum80at2OqUnQ/edit)

Description/Additional Info (Optional): no seriously why isnt 2000n in the thing

**Comment by JetSimon** [comment]
Unless Decstar wants to add it we cannot approve this
