### ISSUE TITLE
Add 2016d to Showcase

### ISSUE THREAD

**Issue by TomatDividedBy0** [campaign-trail-showcase/campaign-trail-showcase.github.io#22]
Mod Name: 2016d: Rubio vs Biden
Best Place to Contact You: schadNF on Discord
Placement: Featured, if declined, community.
Link to Code 1: https://media.tomat0.me/campaigntrail/code1_new.txt
[Link to Code 2 (Rubio/Walker)](https://media.tomat0.me/campaigntrail/code2_rubio-walker.txt)

[Link to Code 2 (Rubio/Kasich)](https://media.tomat0.me/campaigntrail/code2_rubio-kasich.txt)

[Link to Code 2 (Rubio/Cruz)](https://media.tomat0.me/campaigntrail/code2_rubio-cruz.txt)

[Link to Code 2 (Biden/Brown)](https://media.tomat0.me/campaigntrail/code2_biden-brown.txt)

[Link to  Code 2: (Biden/Clinton)](https://media.tomat0.me/campaigntrail/code2_biden-clinton.txt)

[Link to Code 2: (Biden/Webb)](https://media.tomat0.me/campaigntrail/code2_biden-webb.txt)

Description: It's 2016, but with a twist: the establishment got their preferred candidates, and the political environment would go on to be dominated by the issues you'd have expected out of 2015 politics. Will going for the Rust Belt or Sun Belt be the right play? Will Biden's experience or Rubio's youth resonate with voters more? And finally, Trump is not out of the picture: make some wrong steps to aggravate him and he could enter the race as a third party! 

Additional Info: This mod was originally made in 2021, but life got busy and it was taking way too long to make (modding was so much more tedious back then), so I did my best to quickly wrap it up in a working state. Expect its features to be more reflective of that time. Regardless, I got a couple of requests on Reddit to get it added to the loader so I figured I would.

**Comment by JetSimon** [comment]
I noticed that your apostrophes have all been replaced with '. The voting is not done yet but if are going for showcase would you be able to correct those? If you don't want to we can just go community no problem.

<img width="473" alt="image" src="https://github.com/campaign-trail-showcase/campaign-trail-showcase.github.io/assets/622443/97868fd1-8e6d-48d5-baef-f9486fb3da66">

**Comment by JetSimon** [comment]
From Some Guy:

The starting image is a bit stretched. Not a dealbreaker but another thing to change

**Comment by ItsAstronomical** [comment]
I concur with Jet here. I don't see any problems with the mod, other than the text bug regarding commas.

**Comment by TomatDividedBy0** [comment]
> From Some Guy:
> 
> The starting image is a bit stretched. Not a dealbreaker but another thing to change ![image](https://user-images.githubusercontent.com/622443/259626355-5cd2706d-27af-482a-8853-67ac44e496fe.png)

If you have an aspect ratio I should meet let me know. Back when I made this there was like no documented standard for image size iirc. 



> I noticed that your apostrophes have all been replaced with '. The voting is not done yet but if are going for showcase would you be able to correct those? If you don't want to we can just go community no problem.
> 
> See this image for details.
> <img alt="image" width="473" src="https://user-images.githubusercontent.com/622443/259625043-97868fd1-8e6d-48d5-baef-f9486fb3da66.png">

Yeah I can, this is like the fourth time I've had to fix it. For some reason the apostrophes keep replacing themselves with a kind that the CT font doesn't support.

**Comment by TomatDividedBy0** [comment]
Files have been updated to fix the apostrophe issue. Let me know if it comes up again.

**Comment by JetSimon** [comment]
@TomatDividedBy0 Any multiple of 300x160 should be good. 

I still see the apostrophe in Rubio/Walker but the rest seem fixed.
