### ISSUE TITLE
1984b 

### ISSUE THREAD

**Issue by SilentCool96** [campaign-trail-showcase/campaign-trail-showcase.github.io#26]
Mod Name: 1984b (Reagan Assassination) 
Best Place to Contact You: cupojo396
Placement: Do you want your mod to be Featured or Community? If it’s declined as featured would you like it added as a Community mod? sure to both
all links are on here <3: https://docs.google.com/document/d/1h11M0gOCY0EviTViPAoFZbhHvfoREal5xm97aBt77KE/edit?usp=sharing
Description/Additional Info (Optional):  if you think of a better name besides Reagan Assassination I'm down for suggestions, think that one Is bland af also ik they'res way too many fucking vps

**Comment by JetSimon** [comment]
One concern I have if you want to be on the showcase is maybe changing/adding some stuff to make the scenario read more different than 1984.
