### ISSUE TITLE
Ohio 2022 TCT Showcase

### ISSUE THREAD

**Issue by JFNixonbro** [campaign-trail-showcase/campaign-trail-showcase.github.io#35]
Mod Name: Ohio 2022 Tim Ryan
Best Place to Contact You: jfnixon
Link to Code 1: https://raw.githubusercontent.com/TomBoxXD/NCT-Stuff-/Code-1-and-Code-2/2022TimRyan_init.html
Link to Code 2: https://raw.githubusercontent.com/TomBoxXD/NCT-Stuff-/Code-1-and-Code-2/2022TimRyan_RyanDems.html

**Comment by JetSimon** [comment]
Added
