### ISSUE TITLE
1988Hart

### ISSUE THREAD

**Issue by nowherecat65** [campaign-trail-showcase/campaign-trail-showcase.github.io#39]
Mod Name: **1988HART**

Contact me at: .theanswerisme (discord) / mpaintexpert@gmail.com

Link to Code 1: https://gist.githubusercontent.com/nowherecat65/13d6452663f6a7db37640207ff28bb64/raw/ee085324ea97de97e31629bcacbf23649610a8f0/GaryCode1%2520(Showcase)

Link to Code 2: 
Hart/Glenn: https://gist.githubusercontent.com/nowherecat65/13d6452663f6a7db37640207ff28bb64/raw/ee085324ea97de97e31629bcacbf23649610a8f0/Gary88Code%25202%2520HartGlenn

Hart/Tsongas: https://gist.githubusercontent.com/nowherecat65/13d6452663f6a7db37640207ff28bb64/raw/ee085324ea97de97e31629bcacbf23649610a8f0/Gary88Code%25202%2520HartTsongas

Hart/Cisneros: https://gist.githubusercontent.com/nowherecat65/13d6452663f6a7db37640207ff28bb64/raw/ee085324ea97de97e31629bcacbf23649610a8f0/Gary88Code%25202%2520HartCisneros

Hart/Bumpers: 
https://gist.githubusercontent.com/nowherecat65/13d6452663f6a7db37640207ff28bb64/raw/ee085324ea97de97e31629bcacbf23649610a8f0/Gary88Code%25202%2520HartBumpers

**Comment by JetSimon** [comment]
Added
