### ISSUE TITLE
1860 Alt VPs Submission Application

### ISSUE THREAD

**Issue by helios112263** [campaign-trail-showcase/campaign-trail-showcase.github.io#41]
**Mod Name:** 1860 Alt VPs
**Best Place to Contact You:** Discord - helios2001
**Code 1:** https://raw.githubusercontent.com/helios112263/1860-Alt-VPs/main/1860%20Alt%20VPs%20Code%201 
**Lincoln/Hamlin (Canon):** https://raw.githubusercontent.com/helios112263/1860-Alt-VPs/main/1860%20Alt%20VPs%20Lincoln-Hamlin%20(Complete)
**Lincoln/Seward:** https://raw.githubusercontent.com/helios112263/1860-Alt-VPs/main/1860%20Alt%20VPs%20Lincoln-Seward%20(Complete)
**Lincoln/Sumner:** https://raw.githubusercontent.com/helios112263/1860-Alt-VPs/main/1860%20Alt%20VPs%20Lincoln-Sumner%20(Complete)
**Douglas/H.Johnson (Canon):** https://raw.githubusercontent.com/helios112263/1860-Alt-VPs/main/1860%20Alt%20VPs%20Douglas-H.Johnson%20(Complete)
**Douglas/A.Johnson:** https://raw.githubusercontent.com/helios112263/1860-Alt-VPs/main/1860%20Alt%20VPs%20Douglas-A.Johnson%20(Complete)
**Douglas/Wood:** https://raw.githubusercontent.com/helios112263/1860-Alt-VPs/main/1860%20Alt%20VPs%20Douglas-Wood%20(Complete)
**Description/Additional Info (Optional):** Probably self-explanatory.

**Comment by JetSimon** [comment]
While we appreciate the work, we would like to leave the base game scenarios untouched on the site. If this was more than VP changes we could approve.

**Comment by JetSimon** [comment]
We were talking more. We could add a VP only section to the site if you would be interested in that?

**Comment by helios112263** [comment]
Sure that would be fine with me.

**Comment by helios112263** [comment]
Technically I did some rewrites on Code 1 as well but I suppose they aren't
major enough?
