### ISSUE TITLE
2020: Feeling the Bern

### ISSUE THREAD

**Issue by EnvironmentalCap104** [campaign-trail-showcase/campaign-trail-showcase.github.io#43]
Mod Name: 2020: Feeling the Bern
Best Place to Contact You: Environmental_Cap104: Reddit
Link to Code 1: [LINK HERE](https://github.com/EnvironmentalCap104/2020BERN/blob/main/2020BERN%20Code%201.txt)
Link to Code 2 [LINK HERE](https://github.com/EnvironmentalCap104/2020BERN)
Description/Additional Info (Optional): Bernie Sanders wins the Democratic nomination in 2020 and goes up against President Trump. Progressives are ecstatic, but Sanders just needs to appeal to as many moderate and working-class voters as possible to defeat Trump.

**Comment by JetSimon** [comment]
Is there an update to this one incoming? I heard there may be some changes made to make it more different from the base scenario. Wondering if we should hold off until those changes are made.

**Comment by EnvironmentalCap104** [comment]
Idk yet, I'm already kinda committed to my next project but I may go back and make the game harder or change some of the feedback at a later time. I would just put it up so that more people can play the mod.

**Comment by JetSimon** [comment]
Added
