### ISSUE TITLE
2000: Former Presidents (CARTER SIDE ONLY)

### ISSUE THREAD

**Issue by EnvironmentalCap104** [campaign-trail-showcase/campaign-trail-showcase.github.io#46]
Mod Name: 2000: Former Presidents
Best Place to Contact You: Environmental_Cap104
Link to Code 1: [LINK HERE](https://github.com/EnvironmentalCap104/2000FP/blob/main/2000FP%20Code%201.txt)
Link to Code 2 [LINK HERE](https://github.com/EnvironmentalCap104/2000FP)
Description/Additional Info (Optional): The Carter side is the only finished side, and therefore it is the only one playable. This mod will NOT be on the Mod Loader on TNCT until the Bush side comes out in about 2-3 weeks, so it will be playable on CTS when it gets added.

**Comment by JetSimon** [comment]
Added. I know you wanted to get it out because of his birthday, so I'm putting it on, but next time we'd prefer if the mods are finished before being submitted! 

Thanks
