### ISSUE TITLE
Issue with Decimal Separator in "Sea to Shining Sea" Mode

### ISSUE THREAD

**Issue by fraxgut** [campaign-trail-showcase/campaign-trail-showcase.github.io#56]
### Problem Description:
In the "Sea to Shining Sea" mode of TheCampaignTrail, there is an issue with the decimal separator for ad budgets. The game currently assumes a comma (",") as the decimal separator, which works fine for English. However, this causes problems for users with their browser set to Spanish, where the decimal separator is a period ("."). As a result, ad budgets over 9999 fail to work properly.

### Steps to Reproduce:
1. Set the browser language to Spanish.
2. Navigate to the "Sea to Shining Sea" mode.
3. Attempt to set an ad budget over 9999.

### Expected Behavior:
The ad budget should be accepted regardless of the browser's language setting.

### Actual Behavior:
Ad budgets over 9999 do not work when the browser is set to Spanish (possibly other languages as well) due to the decimal separator issue.

**Comment by JetSimon** [comment]
Should be fixed in latest push. Thanks for reporting :)
