### ISSUE TITLE
Add "IMF Loan" Cheat for Additional Funds

### ISSUE THREAD

**Issue by fraxgut** [campaign-trail-showcase/campaign-trail-showcase.github.io#57]
### Feature Request:
Currently, the game provides cheats for various aspects like increasing a candidate's popularity, but there is no cheat available to add more funds directly in the "Sea to Shining Sea" mode. This hampers the testing and experimental gameplay for users. 

### Proposed Solution:
Add a new cheat called "IMF Loan" which instantly provides a substantial amount of money to the player. The code to implement this could be: `e.shining_data.balance += Math.pow(10, 10)`.

### Steps to Implement:
1. Add a new cheat option in the cheat menu.
2. Name it "IMF Loan".
3. Implement the code `e.shining_data.balance += Math.pow(10, 10)` to add a significant amount of money when this cheat is activated.

### Additional Information:
- This addition will enhance the testing and gameplay experience for users who want to experiment with different financial strategies in the game.

**Comment by JetSimon** [comment]
I added an option to the cheat menu to give money in STSS mode. Thanks for the suggestion.

I labelled it a bit more clearly than IMF Loan just so players would know what to expect for sure.
