### ISSUE TITLE
Enhance UI for Ad Spending Functionality in "Sea to Shining Sea" Mode

### ISSUE THREAD

**Issue by fraxgut** [campaign-trail-showcase/campaign-trail-showcase.github.io#58]
### Feature Suggestion:
In the "Sea to Shining Sea" mode, the current process for allocating ad budgets to specific states can be tedious, especially when planning a mass ad campaign. The user has to input a certain amount of money, select a state, and then repeat the process for each additional state. 

### Proposed Solution:
Introduce a more efficient ad spending interface by providing checkboxes for each state. This way, users can allocate the same amount of money to multiple states in a single step. Additionally, include "Select All" and "Select None" buttons for added convenience.

### Steps to Implement:
1. Add checkboxes next to each state in the ad spending interface.
2. Include "Select All" and "Select None" buttons for easy selection management.
3. Implement the logic to distribute the allocated budget to the selected states.

### Expected Benefits:
- Streamlined ad spending process, saving time and effort for users planning large-scale campaigns.
- Improved user experience and efficiency in managing ad budgets.

### Additional Information:
- This enhancement will greatly benefit users looking to conduct comprehensive ad campaigns in "Sea to Shining Sea" mode.

**Comment by JetSimon** [comment]
This is a good suggestion but I am hesitant to make too many changes like this to STSS mode. It was adapted from New Campaign Trail with permission and I'm not sure if Decstar would want us to make those kinds of changes. I'd suggest it to them if you haven't already and see what they say to be safe.

If you want to implement it yourself and make a PR though totally feel free to!
