### ISSUE TITLE
Fix "Answer Hints" Compatibility with UI-Altering Mods (and others)

### ISSUE THREAD

**Issue by fraxgut** [campaign-trail-showcase/campaign-trail-showcase.github.io#59]
### Problem Description:
Currently, the "Answer Hints" cheat does not function correctly in certain mods, especially those that alter the game's user interface, such as the Germany 2021 mod. This diminishes the cheat's effectiveness and usability.

### Proposed Solution:
To address this issue, it is recommended to prioritize the functionality of the "Answer Hints" cheat UI over custom UI elements in mods. This would ensure that the cheat works consistently across different mod environments.

### Additional Error with Specific Mods:
In some cases, such as with the 1992 Perot mod (not currently available on the Showcase), an "(undefined)" error occurs, rendering the cheat non-functional. Investigating and resolving this error will further enhance the cheat's compatibility with various mods.

### Steps to Implement:
1. Identify and prioritize the "Answer Hints" cheat UI over custom UI elements in mods.
2. Investigate and address the "(undefined)" error for specific mods like the 1992 Perot mod.

### Expected Benefits:
- Improved compatibility of the "Answer Hints" cheat with a wider range of mods, enhancing user experience and gameplay options.

### Additional Information:
- This fix will greatly benefit users who enjoy utilizing cheats for various modded scenarios.

**Comment by JetSimon** [comment]
I will ask Nina (Germany mod creator) what she thinks about this. She mentioned wanting to try and make it fit with the mod style before. It may be better to let modders have the freedom to do that should they choose. I will get some community input before doing anything about this.

Again though, if you want to make a PR feel free. This is open!

**Comment by JetSimon** [comment]
After learning how Germany implements it I am of the opinion that the modder should be the one to ensure their mod works with the answer hints. There are many different ways they could modify the look and it would be quite hard to handle every single case.

For Germany I believe it is being looked into by the dev.

Thanks for reporting!
