### ISSUE TITLE
2000FP Update

### ISSUE THREAD

**Issue by EnvironmentalCap104** [campaign-trail-showcase/campaign-trail-showcase.github.io#75]
Mod Name: 2000: Former Presidents
Best Place to Contact You: Environmental_Cap104 (Discord/Reddit)
Link to Code 1: [https://github.com/EnvironmentalCap104/2000FP/blob/main/2000FP_init.html](https://github.com/EnvironmentalCap104/2000FP/blob/main/2000FP_init.html)
Link to Code [2:](https://github.com/EnvironmentalCap104/2000FP/tree/main) https://github.com/EnvironmentalCap104/2000FP/tree/main
Description/Additional Info (Optional): The mod is now complete, as the Bush side has been finished. Everything's the same, but Bush is now playable.

**Comment by JetSimon** [comment]
Updated!

Thanks so much for changing the names to .html. It made it much easier to add.
