### ISSUE TITLE
ROC 2000 Mod 

### ISSUE THREAD

**Issue by EKMG1** [campaign-trail-showcase/campaign-trail-showcase.github.io#80]
Mod Name: ROC 2000
Best Place to Contact You: 
DISCORD 
name: ussroaknoke

Link to Code 1: 
https://github.com/EKMG1/ROC-2000/blob/main/Code%201

Link to Code 2 :
Chen-Lu:
https://github.com/EKMG1/ROC-2000/blob/main/ROC%202000%20Chen-Lu
Lien-Siew:
https://github.com/EKMG1/ROC-2000/blob/main/ROC%202000%20Lien-Siew
Song-Chang:
https://github.com/EKMG1/ROC-2000/blob/main/ROC%202000%20Song-Chang

Description/Additional Info (Optional): 
Election select Icon:
https://github.com/EKMG1/ROC-2000/blob/main/ROC%202000.jpg
I barely use social media like github and discord, reddit, so I'll probably be there very rarely, 
And I don't use github, so I'm confused about the pull request.
I'm doing this mod just for fun. If you have any questions, please contact me on discord.
If you can, please help me upload this mod to showcase and the campaign trail itself so that everyone can play it.

**Comment by JetSimon** [comment]
Added. If you need to make updates use the files on the site because I had to make small changes to make the format fit correctly with the site (just filename and display name changes).
