### ISSUE TITLE
Rocky 64 Pull Request

### ISSUE THREAD

**Issue by WNDIUA** [campaign-trail-showcase/campaign-trail-showcase.github.io#83]
Rocky 64
u/WhatNameDidIUseAgain on Reddit | .whatnamedidiuseagain on Discord

Code 1: https://gist.githubusercontent.com/WNDIUA/649ce27af0f73587894779b30412e20c/raw/5b9d3b3760e0042edd9597d3a8dd3e22b10ca788/gistfile1.txt

Code 2: https://gist.githubusercontent.com/WNDIUA/0af0d3008684b71d164763f9e422111e/raw/5d15d58eb74b12d4e7e005816806544fcdd01e57/gistfile1.txt

got rid of some of the silly writing

**Comment by JetSimon** [comment]
Added. Please use the version added to the site to make any updates because I had to change the filenames and display year to be formatted correctly.
