### ISSUE TITLE
1980 Happy Warrior pull request

### ISSUE THREAD

**Issue by WNDIUA** [campaign-trail-showcase/campaign-trail-showcase.github.io#88]
1980: The Happy Warrior
Discord: .whatnamedidiuseagain
Code 1: https://gist.github.com/WNDIUA/e9f0c9347c0ddda5f620266f5accc65d
Code 2: (Askew): https://gist.github.com/WNDIUA/35c0ca8cb3b0e8effcf2a462ac139b14
Code 2: (Dukakis): https://gist.github.com/WNDIUA/e2fbf00770ae044c032054dcf8bd1b4b
No other information

**Comment by JetSimon** [comment]
Added sorry for delay. This is an issue not a pull request btw. If you do a pull request next time it will be faster.
